# Generated by Django 5.0.6 on 2024-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='focus',
            field=models.CharField(default='no focus specified'),
        ),
        migrations.AddField(
            model_name='note',
            name='length',
            field=models.CharField(default='no length specified'),
        ),
        migrations.AddField(
            model_name='note',
            name='numDays',
            field=models.CharField(default=-1),
        ),
    ]
