# Generated by Django 5.0.6 on 2024-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_note_focus_note_length_note_numdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='workoutPlan',
            field=models.TextField(default='no workout plan'),
        ),
    ]
