# Generated by Django 5.0.6 on 2024-07-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_note_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='workoutPlan',
            field=models.TextField(default='no workout plan'),
        ),
    ]
