# Generated by Django 5.0.6 on 2024-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_note_completed_alter_note_workoutplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='numDays',
            field=models.IntegerField(default=-1),
        ),
    ]
