# Generated by Django 5.0.6 on 2024-07-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_note_numdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='focus',
            field=models.TextField(default='no focus specified'),
        ),
        migrations.AlterField(
            model_name='note',
            name='length',
            field=models.TextField(default='no length specified'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.TextField(default='nameless'),
        ),
        migrations.AlterField(
            model_name='note',
            name='workoutPlan',
            field=models.TextField(default='no workout plan'),
        ),
    ]
