# Generated by Django 5.0.6 on 2024-08-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_note_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
